#!/bin/bash -x
read -p "enter branch name" branchname
git add .
git commit -m "adding $branchname"
git checkout master
git merge "$branchname"
git checkout $branchname
git push origin $branchname
git merge master
git checkout master
git push
